version: '3.8'
services:
  sqlserver:
    build:
      context: .
    ports:
      - "1433:1433"
    volumes:
      - sqlserver_data:/var/opt/mssql
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=YourStrongPassword123
    restart: always

volumes:
  sqlserver_data: